package main

import (
	"github.com/codegangsta/cli"
	"github.com/mesosphere/mom/cluster"
	"github.com/mesosphere/mom/configuration"
	"log"
	"os"
)

func main() {
	conf, err := configuration.Parse()
	if err != nil {
		log.Fatal("Could not parse configuration: ", err)
	}

	app := cli.NewApp()
	app.Name = "mom"
	app.Usage = "Mesos on Mesos cluster testing"
	app.Commands = []cli.Command{
		{
			Name:  "cluster",
			Usage: "Cluster utilies",
			Subcommands: []cli.Command{
				{
					Name:  "launch",
					Usage: "Launched a new mesos cluster. Takes docker image as first argument.",
					Action: func(c *cli.Context) {
						dockerImage := ""
						if len(c.Args()) != 1 {
							log.Fatal("Launch requires docker image")
						}
						dockerImage = c.Args()[0]

						cl := cluster.New(conf)
						err = cl.Launch(dockerImage)
						if err != nil {
							log.Fatal(err)
						}
					},
				},
				{
					Name:  "status",
					Usage: "Shows the status of the running cluster. Takes session id as first argument.",
					Action: func(c *cli.Context) {
						session := ""
						if len(c.Args()) != 1 {
							log.Fatal("Status requires session id")
						}
						session = c.Args()[0]

						cl := cluster.New(conf)
						err = cl.Status(session)
						if err != nil {
							log.Fatal(err)
						}
					},
				},
				{
					Name:  "destroy",
					Usage: "Destroys a running. Takes session id as first argument (generated by cluster launch).",
					Action: func(c *cli.Context) {
						session := ""
						if len(c.Args()) != 1 {
							log.Fatal("Destroy requires session id")
						}
						session = c.Args()[0]

						cl := cluster.New(conf)
						err = cl.Destroy(session)
						if err != nil {
							log.Fatal(err)
						}
					},
				},
			},
		},
	}

	app.Run(os.Args)
}
